name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Check out the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Set the Node.js version for your React app

      - name: Install dependencies
        run: |
          npm install # Install dependencies from package.json

      - name: Build the React app
        run: |
          npm run build # Build the app for production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # GitHub Pages deploy action
        with:
          branch: gh-pages # Deploy to the gh-pages branch
          folder: build # Deploy the contents of the build folder
          token: ${{ secrets.GITHUB_TOKEN }} # Use GitHub's default token for authentication
          cname: jallenhelm.github.io/dvops320 # Optional: Set a custom domain (if applicable)

